# Generated by Django 5.2.6 on 2025-11-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_datasource_db_host_datasource_db_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='internal_schema',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='internal_table',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
