# Generated by Django 5.2.6 on 2025-11-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_alter_externalconnection_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalconnection',
            name='port',
            field=models.IntegerField(default=5432),
        ),
    ]
