# Generated by Django 5.2.6 on 2025-09-14 16:45

import django.db.models.deletion
import fernet_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('FILE', 'Archivo importado'), ('LIVE', 'Conexión en vivo')], default='FILE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internal_schema', models.CharField(blank=True, default='', max_length=120)),
                ('internal_table', models.CharField(blank=True, default='', max_length=120)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL/MariaDB')], default='postgres', max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=5432)),
                ('database', models.CharField(max_length=255)),
                ('username', fernet_fields.fields.EncryptedCharField(max_length=255)),
                ('password', fernet_fields.fields.EncryptedTextField()),
                ('extras', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='ingestion.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('sql', 'SQL')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rows_ingested', models.PositiveIntegerField(default=0)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload', to='ingestion.datasource')),
            ],
        ),
    ]
