# Generated by Django 5.2.6 on 2025-09-23 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción generada por IA')),
                ('chart_type', models.CharField(choices=[('bar', 'Barras'), ('line', 'Líneas'), ('pie', 'Circular'), ('doughnut', 'Dona'), ('scatter', 'Dispersión'), ('radar', 'Radar'), ('area', 'Área')], default='bar', max_length=20)),
                ('source_type', models.CharField(choices=[('AUTO', 'Generado automáticamente'), ('CHAT', 'Generado por chat')], default='AUTO', max_length=10)),
                ('sql_query', models.TextField(help_text='Consulta SQL que genera los datos')),
                ('chart_data', models.JSONField(help_text='Datos JSON para Chart.js {labels: [], datasets: []}')),
                ('chart_config', models.JSONField(default=dict, help_text='Configuración específica del gráfico')),
                ('is_active', models.BooleanField(default=True, help_text='Si se muestra en el dashboard')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagramas', to='ingestion.datasource')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagrama',
                'verbose_name_plural': 'Diagramas',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
