# Generated by Django 5.2.6 on 2025-11-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_diagrama'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='db_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='db_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='db_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='db_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='db_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
