# Generated by Django 5.2.6 on 2025-11-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_alter_datasource_internal_schema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalconnection',
            name='port',
            field=models.IntegerField(default=5433),
        ),
    ]
