# Generated by Django 5.2.6 on 2025-09-22 19:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la regla')),
                ('comparison_operator', models.CharField(choices=[('gt', 'Mayor que (>)'), ('gte', 'Mayor o igual que (>=)'), ('lt', 'Menor que (<)'), ('lte', 'Menor o igual que (<=)'), ('eq', 'Igual a (=)'), ('ne', 'Diferente de (!=)')], max_length=10)),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor umbral')),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_email', models.BooleanField(default=True, verbose_name='Enviar por email')),
                ('email_recipients', models.JSONField(blank=True, default=list, verbose_name='Destinatarios de email')),
                ('send_in_app', models.BooleanField(default=True, verbose_name='Notificación en la app')),
            ],
            options={
                'verbose_name': 'Regla de Alerta',
                'verbose_name_plural': 'Reglas de Alerta',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('acknowledged', 'Reconocida'), ('resolved', 'Resuelta'), ('dismissed', 'Descartada')], default='new', max_length=20)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('message', models.TextField(blank=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.alertrule')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del KPI')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('metric_type', models.CharField(choices=[('sum', 'Suma'), ('avg', 'Promedio'), ('count', 'Conteo'), ('max', 'Máximo'), ('min', 'Mínimo')], max_length=10, verbose_name='Tipo de métrica')),
                ('column_name', models.CharField(max_length=100, verbose_name='Columna a medir')),
                ('filter_conditions', models.JSONField(blank=True, default=dict, verbose_name='Condiciones de filtro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.datasource', verbose_name='Fuente de datos')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
            },
        ),
        migrations.AddField(
            model_name='alertrule',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='notifications.kpi'),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('in_app', 'En la aplicación'), ('sms', 'SMS')], max_length=20)),
                ('recipient', models.CharField(max_length=255, verbose_name='Destinatario')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.alert')),
            ],
            options={
                'verbose_name': 'Log de Notificación',
                'verbose_name_plural': 'Logs de Notificaciones',
            },
        ),
    ]
